services:
  speedtesttracker:
    image: linuxserver/speedtest-tracker
    container_name: speedtest-tracker-app
    hostname: speedtest-tracker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ASSET_URL=${ASSET_URL}
      - APP_LOCALE=${APP_LOCALE}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - CHART_DATETIME_FORMAT=${DATETIME_FORMAT}
      - DATETIME_FORMAT=${DATETIME_FORMAT}
      - DISPLAY_TIMEZONE=${APP_TIMEZONE}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
      - SPEEDTEST_BLOCKED_SERVERS=${SPEEDTEST_BLOCKED_SERVERS}
    volumes:
      - ${SPEEDTEST_CONFIG_FOLDER:-./config}:/config
    restart: unless-stopped
    healthcheck:
      test: curl -fSs APP_URL/api/healthcheck | jq -r .message || exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      local:

networks:
  local:
    name: speedtest_traker-local-network
